const ENDPOINT = 'data.json';

new Vue({
  el: '#app',
  data: {
    coursesData: [
      "",
      "Cenografia 2ª T1 e T2",
      "Figurino 2ª T1 e T2",
      "Teatro musical I 2ª T1 e T2",
      "Teatro musical II 2ª T3 e T4",
      "Dança Contemporânea 4ª T1 e T2",
      "Hip Hop (dança) 4ª T3 e T4",
      "Acrobacia aérea/solo - turma 1 5ª T1 e T2",
      "Acrobacia aérea/solo - turma 2 5ª T3 e T4",
      "Palhaçaria e malabares 5ª T3 e T4",
      "Teatro I - turma 1 5ª T1 e T2",
      "Teatro I - turma 2 5ª T3 e T4",
      "Teatro II 5ª T1 e T2",
      "Jovens Dramaturgos (Escrita dramatúrgica) 5ª T3 e T4",
      "Violão I - turma 1 2ª T1 e T2",
      "Violão I - turma 2 2ª T3 e T4",
      "Bateria I - turma 1 2ª T1 e T2",
      "Bateria I - turma 2 2ª T3 e T4",
      "Piano II 3ª T1 e T2",
      "Trompete/Trombone II 3ª T1 e T2",
      "Clarinete/Flauta II 3ª T1 e T2",
      "Violino/Cello II 3ª T1 e T2",
      "Saxofone II 3ª T1 e T2",
      "Percussão - turma 1 3ª T1 e T2",
      "Acordeon II 3ª T1 e T2",
      "Canto coral - turma 1 3ª T1 e T2",
      "Canto coral - turma 2 3ª T1 e T2",
      "Piano I 3ª T3 e T4",
      "Trompete/Trombone I 3ª T3 e T4",
      "Clarinete/Flauta I 3ª T3 e T4",
      "Violino/Cello I 3ª T3 e T4",
      "Saxofone I 3ª T3 e T4",
      "Hip-hop (Música) 3ª T3 e T4",
      "Percussão - turma 2 3ª T3 e T4",
      "Acordeon I 3ª T3 e T4",
      "Violão II 4ª T1 e T2",
      "Bateria II 4ª T1 e T2",
      "Bateria I - turma 3 4ª T3 e T4",
      "Violão III 5ª T1 e T2",
      "Bateria II 5ª T1 e T2",
      "Baixo 6ª T1 e T2",
      "Cajón 6ª T1 e T2",
      "Tingimento natural 3ª T1 e T2",
      "Arte contemporânea 4ª T1 e T2",
      "Desenho e ilustração - turma 1 4ª T1 e T2",
      "Escultura 4ª T3 e T4",
      "Arte e artesanato 4ª T3 e T4",
      "Desenho e ilustração - turma 2 4ª T3 e T4",
      "Brechó Cabide 5ª T1 e T2",
      "História da Arte 6ª T1 e T2",
      "Produção e criação de moda 6ª T1 e T2",
      "Experimentações artísticas 6ª T3 e T4",
      "Produção e edição audiovisual 5ª T1 e T2",
      "Crítica de cinema 5ª T3 e T4",
      "Futsal Iniciante 3ª T3 e T4",
      "Futsal Equipe Feminina 4ª T3 e T4",
      "Futsal Equipe Masculina 4ª T1 e T2",
      "Futsal Equipe Mista 6ª T1 e T2",
      "Basquete Iniciante 2ª T3 e T4",
      "Basquete Equipe Feminina 5ª T3 e T4",
      "Basquete Equipe Masculina 3ª T3 e T4",
      "Basquete Equipe Mista 6ª T3 e T4",
      "Voleibol Iniciante 5ª T3 e T4",
      "Voleibol Equipe Feminina 5ª T1 e T2",
      "Voleibol Equipe Masculina 3ª T1 e T2",
      "Voleibol Equipe Mista 2ª T1 e T2",
      "Handebol Iniciante 3ª T1 e T2",
      "Handebol Equipe Feminina 2ª T1 e T2",
      "Handebol Equipe Masculina 2ª T3 e T4",
      "Handebol Equipe Mista 4ª T3 e T4",
      "Karate Iniciante 3ª e 6ª T3",
      "Karate Equipe - Turma 1 4ª T1 e T2",
      "Karate Equipe - Turma 2 6ª T1 e T2",
      "Dança Iniciante 4ª e 6ª T2",
      "Dança Equipe - Turma 1 3ª T3 e T4",
      "Dança Equipe - Turma 2 5ª T3 e T4",
      "Natação Iniciante 3ª e 5ª T3",
      "Natação Intermediário 2ª e 4ª T3",
      "Natação Equipe - Turma 1 2ª T1 e T2",
      "Natação Equipe - Turma 2 4ª T1 e T2",
      "Frisbee Iniciante 3ª e 5ª T1",
      "Frisbee Equipe 4ª e 6ª T1",
      "Esportes de Raquete - Turma 1 2ª T3 e T4",
      "Esportes de Raquete - Turma 2 4ª T3 e T4",
      "Pilates 2ª e 5ª T1",
      "Bio Mix Zen - Turma 1 4ª e 6ª T1",
      "Bio Mix Zen - Turma 2 4ª e 6ª T3",
      "Ginástica 3ª e 5ª T2",
      "Atletismo 3ª e 5ª T1",
      "Current Affairs 4ª T1 e T2",
      "International Exams Practice 3ª T1 e T2",
      "BookTubers 3ª e 5ª T1",
      "Writing the Basics 4ª T1 e T2",
      "Chitchatting 3ª T3 e T4",
      "Espanhol 1 (turma 1) 2ª e 4ª T1",
      "Espanhol 1 (turma 2) 2ª e 4ª T3",
      "Espanhol 1 (turma 3) 2ª e 4ª T4",
      "Espanhol 1 (turma 4) 3ª e 5ª T4",
      "Espanhol 2 (turma 1) 3ª e 5ª T1",
      "Espanhol 2 (turma 2) 3ª e 5ª T2",
      "Espanhol 2 (turma 3) 3ª e 5ª T3",
      "Espanhol 3 (turma 1) 2º T1 e T2",
      "Espanhol para Vestibulares 5ª T1 e T2",
      "Francês 1 (turma 1) 2ª e 4ª T1",
      "Francês 1 (turma 2) 2ª e 4ª T2",
      "Francês 1 (turma 3) 3ª e 5ª T1",
      "Francês 1 (turma 4) 3ª e 5ª T2",
      "Francês 1 (turma 5) 3ª e 5ª T3",
      "Francês 2 (turma 1) 2ª e 4ª T3",
      "Francês 2 (turma 2) 2ª e 4ª T4",
      "Francês 2 (turma 3) 6ª T1 e T2",
      "Francês 3 (turma 1) 6ª T3 e T4",
      "Alemão 1 (turma 1) 2ª e 4ª T1",
      "Alemão 1 (turma 2) 2ª e 4ª T2",
      "Alemão 1 (turma 3) 2ª e 4ª T3",
      "Alemão 1 (turma 4) 2ª e 4ª T4",
      "Alemão 2 (turma 1) 3ª e 5ª T1",
      "Alemão 2 (turma 2) 3ª e 5ª T2",
      "Alemão 2 (turma 3) 3ª e 5ª T3",
      "Alemão 3 (turma 1) 3ª e 5ª T4",
      "Funções Reais 4ª T1 e T2",
      "Funções Reais 5ª T1 e T2",
      "Estatística aplicada às ciências 3ª T3 e T4",
      "Introdução ao Cálculo 6ª T1 e T2",
      "Introdução ao Cálculo 4ª T1 e T2",
      "Biologia Humana 2ª T1 e T2",
      "Biologia Humana 4ª T1 e T2",
      "Física Aplicada 3ª T1 e T2",
      "Ecologia Aplicada 5ª T3 e T4",
      "Química Aplicada 4ª T1 e T2",
      "Antropologia das Juventudes 2ª T1 e T2",
      "Ética Contemporânea 6ª T1 e T2",
      "Antropologia dos Modos de Regulação Social 3ª T1 e T2",
      "Geografia: Reflexões sobre Contemporâneo 3ª T1 e T2",
      "Historia do Tempo Presente 3ª T1 e T2",
      "Historia das Religiões 4ª T1 e T2",
      "Texto, argumentação e discurso 6ª T3 e T4",
      "Texto, argumentação e discurso 2ª T1 e T2",
      "Literatura inquieta: tendências contemporâneas 6ª T1 e T2",
      "Leitura e interpretação 5ª T3 e T4",
      "Laboratório de escrita 3ª T1 e T2"
    ],
    repos: [],
    filter:""
  },
  methods:{
    printDocument: function(){
      window.print();
    }
  },
  mounted() {
    axios
      .get(ENDPOINT)
      .then(response => response.data)
      .then(data => Vue.set(this, 'repos', data));
  },
  computed: {
    list() {
      const filter = this.filter;
      const list = _.orderBy(this.repos, "NOME");
      return _.filter(list, repo => repo.CURSO.indexOf(filter) >= 0);
    }
  },
});
